# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8wzySnjNQs3URBVOiwGUo5OElZcteX2
"""

import streamlit as st
import pandas as pd
import joblib
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime
from fpdf import FPDF
import base64
import numpy as np
import io
import time

# ---------------------------------------------------------
# SETUP & CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="Smart Loan Advisor",
    page_icon="🏦",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for better UI - FIXED METRIC WIDTH
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        color: #1E3A8A;
        font-weight: 700;
        margin-bottom: 1rem;
    }
    .sub-header {
        font-size: 1.5rem;
        color: #374151;
        font-weight: 600;
        margin-top: 1.5rem;
        margin-bottom: 1rem;
    }
    .tip-box {
        background-color: #F0F9FF;
        padding: 1rem;
        border-radius: 8px;
        border-left: 4px solid #3B82F6;
        margin: 1rem 0;
    }
    .success-box {
        background-color: #D1FAE5;
        padding: 1rem;
        border-radius: 8px;
        border-left: 4px solid #10B981;
        margin: 0.5rem 0;
    }
    .warning-box {
        background-color: #FEF3C7;
        padding: 1rem;
        border-radius: 8px;
        border-left: 4px solid #F59E0B;
        margin: 0.5rem 0;
    }
    .info-box {
        background-color: #E0F2FE;
        padding: 1rem;
        border-radius: 8px;
        border-left: 4px solid #0EA5E9;
        margin: 0.5rem 0;
    }
    /* Fix metric width to prevent text cutoff */
    .stMetric {
        min-height: 100px;
    }
    .stMetric > div {
        min-height: 85px;
    }
    .stMetric label {
        font-size: 0.95rem !important;
        font-weight: 600 !important;
    }
    .stMetric .css-1r6slb0 {
        overflow: visible !important;
        white-space: normal !important;
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# INITIALIZE SESSION STATE
# ---------------------------------------------------------
if 'last_submission' not in st.session_state:
    st.session_state.last_submission = 0
if 'results' not in st.session_state:
    st.session_state.results = None

# ---------------------------------------------------------
# UK FINANCIAL STANDARDS
# ---------------------------------------------------------
CONVERSION_RATE = 100
UK_AVERAGE_SALARY = 35000
UK_AVERAGE_HOUSE_PRICE = 250000
UK_ASSET_MULTIPLIER = 5

# ---------------------------------------------------------
# FEATURE ENGINEERING FUNCTIONS
# ---------------------------------------------------------
def create_credit_features(df):
    """Create engineered features for credit assessment"""
    df_engineered = df.copy()

    # Monthly calculations
    monthly_income = df_engineered['income_annum'] / 12
    monthly_loan_payment = (df_engineered['loan_amount'] / df_engineered['loan_term']) / 12

    # Key ratios
    df_engineered['monthly_payment_ratio'] = (monthly_loan_payment / monthly_income) * 100
    df_engineered['asset_coverage'] = (df_engineered['total_assets'] / df_engineered['loan_amount']) * 100
    df_engineered['loan_to_income'] = (df_engineered['loan_amount'] / df_engineered['income_annum']) * 100

    # Credit score categories
    def categorize_credit_score(score):
        if score >= 900:
            return 'Excellent'
        elif score >= 800:
            return 'Very Good'
        elif score >= 700:
            return 'Good'
        elif score >= 600:
            return 'Fair'
        else:
            return 'Needs Improvement'

    df_engineered['credit_category'] = df_engineered['credit_score'].apply(categorize_credit_score)

    # Stability score
    df_engineered['stability_score'] = 0
    df_engineered.loc[df_engineered['self_employed'] == 'No', 'stability_score'] += 30
    df_engineered.loc[df_engineered['education'] == 'Graduate', 'stability_score'] += 20
    df_engineered.loc[df_engineered['no_of_dependents'] <= 2, 'stability_score'] += 10

    return df_engineered

def calculate_matching_score(row):
    """Calculate matching score (0-100) based on credit profile"""
    score = 0

    # 1. Credit Score Component
    if row['credit_score'] >= 900:
        score += 40
    elif row['credit_score'] >= 800:
        score += 35
    elif row['credit_score'] >= 700:
        score += 30
    elif row['credit_score'] >= 600:
        score += 20
    else:
        score += 10

    # 2. Monthly Payment Affordability
    if row['monthly_payment_ratio'] <= 25:
        score += 25
    elif row['monthly_payment_ratio'] <= 35:
        score += 20
    elif row['monthly_payment_ratio'] <= 45:
        score += 15
    elif row['monthly_payment_ratio'] <= 55:
        score += 10
    else:
        score += 5

    # 3. Asset Security
    if row['asset_coverage'] >= 250:
        score += 20
    elif row['asset_coverage'] >= 175:
        score += 16
    elif row['asset_coverage'] >= 125:
        score += 12
    elif row['asset_coverage'] >= 75:
        score += 8
    else:
        score += 4

    # 4. Stability Factors
    score += min(row['stability_score'], 15)

    # 5. Risk adjustments
    if row['self_employed'] == 'Yes' and row['income_annum'] < 30000:
        score -= 10

    if row['no_of_dependents'] > 3:
        score -= 5

    if row['loan_term'] > 7 and row['loan_amount'] < 150000:
        score -= 3

    return min(max(score, 0), 100)

def get_detailed_recommendation(score, probability, features):
    """Generate personalized recommendations"""
    recommendations = []

    if score >= 80:
        recommendations.append({
            "title": "Strong Candidate",
            "message": "Your financial profile meets our premium criteria for UK lending.",
            "actions": ["Proceed with full application", "Expect competitive interest rates", "Fast-track processing available"],
            "box_type": "success"
        })
    elif score >= 65:
        recommendations.append({
            "title": "Good Candidate",
            "message": "Your application has good approval chances in the UK market.",
            "actions": ["Complete full application", "Prepare 3 months of UK bank statements", "Have UK property documents ready"],
            "box_type": "success"
        })
    elif score >= 50:
        recommendations.append({
            "title": "Needs Review",
            "message": "Some areas need attention for better UK approval odds.",
            "actions": ["Consider a UK-based co-applicant", "Reduce loan amount by 10-15%", "Provide additional UK income proof"],
            "box_type": "warning"
        })
    else:
        recommendations.append({
            "title": "Needs Improvement",
            "message": "We recommend improving your profile before UK application.",
            "actions": ["Build UK credit history for 6 months", "Increase UK savings balance", "Reduce existing UK debts"],
            "box_type": "warning"
        })

    # Specific tips based on features
    if features.get('monthly_payment_ratio', 0) > 40:
        recommendations.append({
            "title": "Payment Affordability",
            "message": "Your monthly payment is high relative to UK income standards.",
            "actions": ["Consider longer loan term", "Look for UK government schemes", "Increase deposit amount"],
            "box_type": "info"
        })

    if features.get('credit_score', 0) < 700:
        recommendations.append({
            "title": "Credit Score",
            "message": "UK credit score can be improved for better rates.",
            "actions": ["Register on UK electoral roll", "Keep credit utilisation below 30%", "Avoid new UK credit applications"],
            "box_type": "info"
        })

    if features.get('asset_coverage', 0) < 125:
        recommendations.append({
            "title": "Asset Coverage",
            "message": "More UK-based assets would strengthen your application.",
            "actions": ["Include UK property equity", "Show UK investment portfolios", "Document UK pension funds"],
            "box_type": "info"
        })

    return recommendations

# ---------------------------------------------------------
# PDF REPORT GENERATION - SIMPLIFIED FIX
# ---------------------------------------------------------
def generate_simple_pdf_report(applicant_data, results, features):
    """Generate a simple text-based PDF report"""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()

    # Add UTF-8 compatible font (using standard font that supports pound symbol)
    pdf.add_font('DejaVu', '', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', uni=True)

    # Title
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'UK Loan Pre-Approval Report', 0, 1, 'C')

    # Date
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, f'Generated: {datetime.now().strftime("%d/%m/%Y %H:%M")}', 0, 1, 'C')
    pdf.ln(10)

    # Applicant Information (without pound symbol)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Applicant Information', 0, 1)
    pdf.set_font('Arial', '', 10)

    info_lines = [
        f"Credit Score: {applicant_data['credit_score']}",
        f"Annual Income: GBP {applicant_data['income_annum']:,}",
        f"Loan Amount: GBP {applicant_data['loan_amount']:,}",
        f"Loan Term: {applicant_data['loan_term']} years",
        f"Employment: {applicant_data['self_employed']}",
        f"Education: {applicant_data['education']}"
    ]

    for line in info_lines:
        pdf.cell(0, 8, line, 0, 1)

    pdf.ln(5)

    # Assessment Results
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Assessment Results', 0, 1)
    pdf.set_font('Arial', '', 10)

    result_lines = [
        f"Matching Score: {results['matching_score']}/100",
        f"Approval Probability: {results['approval_probability']:.1f}%",
        f"Status: {results['status']}"
    ]

    for line in result_lines:
        pdf.cell(0, 8, line, 0, 1)

    pdf.ln(5)

    # Key Metrics
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Financial Health Check', 0, 1)
    pdf.set_font('Arial', '', 10)

    metric_lines = [
        f"Monthly Payment Ratio: {features['monthly_payment_ratio']:.1f}%",
        f"Asset Coverage: {features['asset_coverage']:.1f}%",
        f"Credit Category: {features['credit_category']}"
    ]

    for line in metric_lines:
        pdf.cell(0, 8, line, 0, 1)

    pdf.ln(5)

    # Recommendations
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Recommendations', 0, 1)
    pdf.set_font('Arial', '', 10)

    for i, rec in enumerate(results['recommendations'][:2]):
        pdf.multi_cell(0, 6, f"{i+1}. {rec['message']}")
        pdf.ln(2)

    # Save to bytes
    return pdf.output(dest='S').encode('latin-1')

# ---------------------------------------------------------
# VISUALIZATION FUNCTIONS
# ---------------------------------------------------------
def create_score_gauge(score):
    """Create a gauge chart for matching score"""
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=score,
        domain={'x': [0, 1], 'y': [0, 1]},
        title={'text': "Profile Match Score"},
        gauge={
            'axis': {'range': [None, 100]},
            'bar': {'color': "#3B82F6"},
            'steps': [
                {'range': [0, 50], 'color': "#EF4444"},
                {'range': [50, 70], 'color': "#F59E0B"},
                {'range': [70, 85], 'color': "#10B981"},
                {'range': [85, 100], 'color': "#047857"}
            ],
            'threshold': {
                'line': {'color': "black", 'width': 4},
                'thickness': 0.75,
                'value': 70
            }
        }
    ))
    fig.update_layout(height=300, margin=dict(l=20, r=20, t=50, b=20))
    return fig

def create_feature_radar(features):
    """Create radar chart for key features"""
    categories = ['Credit Score', 'Affordability', 'Asset Security', 'Stability']
    values = [
        min(100, features['credit_score'] / 9.99),
        100 - min(100, features['monthly_payment_ratio']),
        min(100, features['asset_coverage'] / 2.5),
        min(100, features['stability_score'] / 45 * 100)
    ]

    fig = go.Figure(data=go.Scatterpolar(
        r=values + [values[0]],
        theta=categories + [categories[0]],
        fill='toself',
        fillcolor='rgba(59, 130, 246, 0.3)',
        line_color='rgb(59, 130, 246)'
    ))

    fig.update_layout(
        polar=dict(
            radialaxis=dict(
                visible=True,
                range=[0, 100]
            )),
        showlegend=False,
        height=300,
        margin=dict(l=50, r=50, t=30, b=30)
    )
    return fig

# ---------------------------------------------------------
# MAIN APPLICATION
# ---------------------------------------------------------
def main():
    # Header
    st.markdown('<h1 class="main-header">UK Smart Loan Advisor</h1>', unsafe_allow_html=True)
    st.markdown("""
    <div class="tip-box">
    This tool provides a preliminary assessment based on UK lending criteria.
    Final approval requires full documentation and verification by a UK lender.
    </div>
    """, unsafe_allow_html=True)

    # Sidebar for inputs - UK STANDARDS
    with st.sidebar:
        st.markdown('<h3 class="sub-header">Your Information</h3>', unsafe_allow_html=True)

        # Personal Information - UK FOCUSED
        st.subheader("Personal Details")
        credit_score = st.slider(
            "Credit Score (UK 0-999)",
            min_value=0,
            max_value=999,
            value=750,
            help="UK credit scores range from 0-999"
        )

        income_annum = st.number_input(
            "Annual Income (£)",
            min_value=15000,
            value=35000,
            step=5000,
            help="Typical UK salaries range from £20k-£60k"
        )

        loan_amount = st.number_input(
            "Loan Amount (£)",
            min_value=5000,
            value=25000,
            step=5000,
            help="Common UK loan amounts"
        )

        loan_term = st.slider(
            "Loan Term (Years)",
            min_value=1,
            max_value=30,
            value=5,
            help="Typical UK loan terms"
        )

        no_of_dependents = st.selectbox(
            "Number of Dependents",
            options=[0, 1, 2, 3, 4, "5 or more"],
            index=1
        )

        # Employment & Education
        col1, col2 = st.columns(2)
        with col1:
            self_employed = st.radio(
                "Employment Type",
                ["Employed", "Self-Employed"]
            )
        with col2:
            education = st.radio(
                "Education",
                ["Graduate", "Not Graduate"]
            )

        # Assets - UK FOCUSED
        st.markdown('<h3 class="sub-header">Your Assets</h3>', unsafe_allow_html=True)
        total_assets = st.number_input(
            "Total Assets (£)",
            min_value=0,
            value=50000,
            step=10000,
            help="Total value of all assets"
        )

        if st.checkbox("Show asset breakdown", value=False):
            st.info("""
            **UK Asset Breakdown (for model compatibility):**
            - 50% residential_assets_value
            - 25% commercial_assets_value
            - 15% luxury_assets_value
            - 10% bank_asset_value
            """)

        # Rate limiting
        current_time = time.time()
        time_since_last = current_time - st.session_state.last_submission

        if time_since_last < 5 and st.session_state.results is not None:
            remaining = 5 - time_since_last
            st.warning(f"Please wait {remaining:.1f} seconds")
            calculate_disabled = True
        else:
            calculate_disabled = False

        # Calculate Button
        calculate_btn = st.button(
            "Check Eligibility",
            type="primary",
            disabled=calculate_disabled,
            use_container_width=True
        )

    # Main Content Area
    if calculate_btn:
        # Update last submission time
        st.session_state.last_submission = time.time()

        # Validate inputs
        validation_errors = []
        if loan_term > 30:
            validation_errors.append("Loan term cannot exceed 30 years")
        if income_annum <= 0:
            validation_errors.append("Annual income must be positive")
        if not (0 <= credit_score <= 999):
            validation_errors.append("Credit score must be between 0-999")

        if validation_errors:
            for error in validation_errors:
                st.error(error)
            return

        # Asset allocation using ACTUAL COLUMN NAMES
        ASSET_ALLOCATION = {
            "residential_assets_value": 0.50,
            "commercial_assets_value": 0.25,  # Updated to match your data
            "luxury_assets_value": 0.15,
            "bank_asset_value": 0.10
        }

        # Convert to model scale
        residential_assets = int((total_assets * ASSET_ALLOCATION['residential_assets_value']) * CONVERSION_RATE)
        commercial_assets = int((total_assets * ASSET_ALLOCATION['commercial_assets_value']) * CONVERSION_RATE)
        luxury_assets = int((total_assets * ASSET_ALLOCATION['luxury_assets_value']) * CONVERSION_RATE)
        bank_assets = int((total_assets * ASSET_ALLOCATION['bank_asset_value']) * CONVERSION_RATE)

        # Prepare input data for model
        model_input_data = {
            "credit_score": credit_score,
            "income_annum": int(income_annum * CONVERSION_RATE),
            "loan_amount": int(loan_amount * CONVERSION_RATE),
            "loan_term": loan_term,
            "no_of_dependents": no_of_dependents if isinstance(no_of_dependents, int) else 5,
            "self_employed": "Yes" if self_employed == "Self-Employed" else "No",
            "education": education,
            "residential_assets_value": residential_assets,
            "commercial_assets_value": commercial_assets,
            "luxury_assets_value": luxury_assets,
            "bank_asset_value": bank_assets,
            "total_assets": int(total_assets * CONVERSION_RATE)
        }

        # UK display data
        uk_display_data = {
            "credit_score": credit_score,
            "income_annum": income_annum,
            "loan_amount": loan_amount,
            "loan_term": loan_term,
            "no_of_dependents": no_of_dependents if isinstance(no_of_dependents, int) else 5,
            "self_employed": self_employed,
            "education": education,
            "total_assets": total_assets
        }

        # Create DataFrame for model
        df_input = pd.DataFrame([model_input_data])

        # Feature engineering
        df_features = create_credit_features(df_input)

        # Calculate matching score
        matching_score = calculate_matching_score(df_features.iloc[0])

        # Load model and predict
        try:
            model = joblib.load("best_xgb_model.pkl")
            feature_columns = joblib.load("feature_columns.pkl")

            # Prepare features for model
            X_input = df_input.drop(columns=['total_assets'])
            X_input = pd.get_dummies(X_input)
            X_input = X_input.reindex(columns=feature_columns, fill_value=0)

            # Get prediction
            approval_probability = model.predict_proba(X_input)[0, 1] * 100
            prediction = model.predict(X_input)[0]

        except Exception as e:
            st.error(f"Model error: {str(e)}")
            # Fallback
            approval_probability = max(20, min(95, matching_score * 0.85))
            prediction = 1 if matching_score >= 60 else 0

        # Generate recommendations
        recommendations = get_detailed_recommendation(
            matching_score,
            approval_probability,
            df_features.iloc[0].to_dict()
        )

        # Determine status
        if matching_score >= 80:
            status = "Excellent"
            status_box = "success"
        elif matching_score >= 65:
            status = "Good"
            status_box = "success"
        elif matching_score >= 50:
            status = "Needs Review"
            status_box = "warning"
        else:
            status = "Improve Profile"
            status_box = "warning"

        # Store results
        st.session_state.results = {
            'matching_score': matching_score,
            'approval_probability': approval_probability,
            'prediction': prediction,
            'status': status,
            'status_box': status_box,
            'recommendations': recommendations,
            'applicant_data': uk_display_data,
            'features': df_features.iloc[0].to_dict()
        }

    # Display results if available
    if st.session_state.results:
        results = st.session_state.results

        # Results Header
        st.markdown('<h2 class="sub-header">Your UK Eligibility Report</h2>', unsafe_allow_html=True)

        # Key Metrics in Columns - SHORTENED LABELS
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric(
                label="Match Score",
                value=f"{results['matching_score']}/100"
            )
            # Show status in colored box
            if results['status_box'] == "success":
                st.success(results['status'])
            elif results['status_box'] == "warning":
                st.warning(results['status'])

        with col2:
            st.metric(
                label="Approval %",
                value=f"{results['approval_probability']:.0f}%"
            )

        with col3:
            action_value = "Apply Now" if results['matching_score'] >= 65 else "Improve"
            st.metric(
                label="Action",
                value=action_value
            )

        with col4:
            # SHORTENED processing times
            if results['matching_score'] >= 70:
                time_value = "2-4 Days"
            elif results['matching_score'] >= 50:
                time_value = "5-10 Days"
            else:
                time_value = "Review"
            st.metric(
                label="Processing",
                value=time_value
            )

        # Charts Row
        col1, col2 = st.columns(2)

        with col1:
            st.plotly_chart(create_score_gauge(results['matching_score']), use_container_width=True)

        with col2:
            st.plotly_chart(create_feature_radar(results['features']), use_container_width=True)

        # Financial Health Indicators
        st.markdown('<h3 class="sub-header">Financial Health Check</h3>', unsafe_allow_html=True)

        col1, col2, col3 = st.columns(3)

        with col1:
            payment_ratio = results['features']['monthly_payment_ratio']
            st.write("**Payment Affordability**")
            uk_target = 35
            progress_value = max(0.0, min(1.0, (uk_target - min(payment_ratio, uk_target)) / uk_target))
            st.progress(
                progress_value,
                text=f"£{results['applicant_data']['loan_amount']/results['applicant_data']['loan_term']/12:.0f}/month"
            )
            st.caption(f"{payment_ratio:.1f}% of income")

        with col2:
            asset_coverage = results['features']['asset_coverage']
            st.write("**Asset Security**")
            progress_value = min(1.0, asset_coverage / 250)
            st.progress(
                progress_value,
                text=f"£{results['applicant_data']['total_assets']:,}"
            )
            st.caption(f"{asset_coverage:.1f}% coverage")

        with col3:
            stability = results['features']['stability_score']
            st.write("**Stability**")
            progress_value = min(1.0, stability / 60)
            st.progress(
                progress_value,
                text=f"{stability}/60"
            )
            st.caption("Employment & education")

        # Personalized Recommendations
        st.markdown('<h3 class="sub-header">Your Action Plan</h3>', unsafe_allow_html=True)

        for i, rec in enumerate(results['recommendations'][:4]):
            if rec['box_type'] == "success":
                box_class = "success-box"
            elif rec['box_type'] == "warning":
                box_class = "warning-box"
            else:
                box_class = "info-box"

            with st.expander(f"{rec['title']}", expanded=i==0):
                st.markdown(f"<div class='{box_class}'>", unsafe_allow_html=True)
                st.write(f"**{rec['message']}**")
                st.write("")
                st.write("**Suggested Steps:**")
                for action in rec['actions']:
                    st.write(f"• {action}")
                st.markdown("</div>", unsafe_allow_html=True)

        # Next Steps
        st.markdown('<h3 class="sub-header">Next Steps</h3>', unsafe_allow_html=True)

        if results['matching_score'] >= 65:
            with st.container():
                st.markdown("""
                <div class="success-box">
                <h4>UK Application Pathway</h4>
                <ol>
                <li>Complete UK application online</li>
                <li>Upload UK bank statements</li>
                <li>Soft credit check</li>
                <li>Decision in 2-4 days</li>
                </ol>
                </div>
                """, unsafe_allow_html=True)
        else:
            with st.container():
                st.markdown("""
                <div class="warning-box">
                <h4>Improvement Pathway</h4>
                <ol>
                <li>Review UK credit report</li>
                <li>Build UK credit history</li>
                <li>Increase UK savings</li>
                <li>Get UK financial advice</li>
                </ol>
                </div>
                """, unsafe_allow_html=True)

        # PDF Report Generation - FIXED
        st.markdown('<h3 class="sub-header">Download Report</h3>', unsafe_allow_html=True)

        col1, col2 = st.columns([3, 1])

        with col1:
            st.info("Download a detailed PDF report with your UK assessment results.")

        with col2:
            try:
                # Use the simple PDF generator
                pdf_bytes = generate_simple_pdf_report(
                    results['applicant_data'],
                    results,
                    results['features']
                )

                b64 = base64.b64encode(pdf_bytes).decode()
                href = f'<a href="data:application/pdf;base64,{b64}" download="UK_Loan_Report_{datetime.now().strftime("%Y%m%d")}.pdf" style="background-color: #3B82F6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;">Download PDF</a>'
                st.markdown(href, unsafe_allow_html=True)
            except Exception as e:
                # Better error message
                st.error("PDF generation requires DejaVu font. Please install with: sudo apt-get install fonts-dejavu")
                # Alternative: offer text download
                st.download_button(
                    label="Download Text Report",
                    data=f"""
UK Loan Assessment Report
Generated: {datetime.now().strftime("%d/%m/%Y")}

Applicant Information:
Credit Score: {results['applicant_data']['credit_score']}
Annual Income: £{results['applicant_data']['income_annum']:,}
Loan Amount: £{results['applicant_data']['loan_amount']:,}
Loan Term: {results['applicant_data']['loan_term']} years
Employment: {results['applicant_data']['self_employed']}
Education: {results['applicant_data']['education']}

Assessment Results:
Matching Score: {results['matching_score']}/100
Approval Probability: {results['approval_probability']:.1f}%
Status: {results['status']}

Key Metrics:
Monthly Payment Ratio: {results['features']['monthly_payment_ratio']:.1f}%
Asset Coverage: {results['features']['asset_coverage']:.1f}%
Credit Category: {results['features']['credit_category']}

Recommendations:
{chr(10).join([rec['message'] for rec in results['recommendations'][:2]])}
                    """,
                    file_name=f"UK_Loan_Report_{datetime.now().strftime('%Y%m%d')}.txt",
                    mime="text/plain"
                )

    else:
        # Welcome screen
        col1, col2 = st.columns([2, 1])

        with col1:
            st.markdown("""
            ### How It Works

            1. **Enter Details** - Provide your UK financial information
            2. **UK Assessment** - Check against UK lending criteria
            3. **Get Your Score** - See your matching score
            4. **Get UK Tips** - Tailored advice for UK market
            5. **Download Report** - Share with advisors

            ### What We Check

            **UK Credit Health** - Your UK credit score
            **Affordability** - Monthly repayment capacity
            **Asset Security** - UK-based assets
            **Stability** - Employment, education
            **Risk Factors** - Self-employment, dependents

            ### Benefits

            • **Free UK Assessment** - No credit impact
            • **UK Market Specific** - Tailored advice
            • **Educational** - Learn UK lending practices
            """)

        with col2:
            st.markdown("""
            <div style="background-color: #F0F9FF; padding: 1.5rem; border-radius: 10px; margin-top: 2rem;">
            <h4>UK Quick Tips</h4>
            <ul style="padding-left: 1.2rem;">
            <li>UK credit score 700+ for best rates</li>
            <li>Monthly payments under 35% of income</li>
            <li>Assets cover 125%+ of loan amount</li>
            <li>Register on electoral roll</li>
            </ul>
            </div>
            """, unsafe_allow_html=True)

    # Footer
    st.markdown("---")
    st.markdown("""
    <div style="text-align: center; color: #6B7280; font-size: 0.9rem;">
    <p><strong>UK Disclaimer:</strong> Preliminary assessment only. Final approval subject to UK credit checks and lender policies. Not a guarantee of approval.</p>
    <p>© 2026 Smart solution to tough data. UK representative APR 4.9% - 19.9%.</p>
    </div>
    """, unsafe_allow_html=True)

if __name__ == "__main__":
    main()